auth0:
  audience: http://gateway
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-f0azx6aq.us.auth0.com/
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: compte-id
          uri: lb://comptes
          predicates:
            - Path=/comptes/**
        - id: carte-id
          uri: lb://cartes
          predicates:
            - Path=/cartes/**
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
